---
- name: download touch kernel modules
  get_url: url={{ item.url }} dest=/usr/local/src/pitft/ mode=0440
  with_items:
    - http://adafruit-download.s3.amazonaws.com/libraspberrypi-bin-adafruit.deb
    - http://adafruit-download.s3.amazonaws.com/libraspberrypi-dev-adafruit.deb
    - http://adafruit-download.s3.amazonaws.com/libraspberrypi-doc-adafruit.deb
    - http://adafruit-download.s3.amazonaws.com/libraspberrypi0-adafruit.deb
    - http://adafruit-download.s3.amazonaws.com/raspberrypi-bootloader-adafruit-112613.deb

# - apt: deb=/usr/local/src/{{ item.name }}
#   with_items: touch_kernel_modules

- name: Turn off accelerated X framebuffer
  command: sudo mv /usr/share/11/xorg.conf.d/99-fbturbo.conf ~
