---
- name: download touch kernel modules
  get_url: url={{ item.url }} dest=/usr/local/src mode=0440
  with_items: touch_kernel_modules

- apt: deb=/usr/local/src/{{ item.name }}
  with_items: touch_kernel_modules

- name: Turn off accelerated X framebuffer
  command: sudo mv /usr/share/11/xorg.conf.d/99-fbturbo.conf ~

touch_kernel_modules:
    - url: http://adafruit-download.s3.amazonaws.com/libraspberrypi-bin-adafruit.deb,
      name: libraspberrypi-bin-adafruit.deb
    - url: http://adafruit-download.s3.amazonaws.com/libraspberrypi-dev-adafruit.deb,
      name: libraspberrypi-dev-adafruit.deb
    - url: http://adafruit-download.s3.amazonaws.com/libraspberrypi-doc-adafruit.deb,
      name: libraspberrypi-doc-adafruit.deb
    - url: http://adafruit-download.s3.amazonaws.com/libraspberrypi0-adafruit.deb,
      name: libraspberrypi0-adafruit.deb
    - url: http://adafruit-download.s3.amazonaws.com/raspberrypi-bootloader-adafruit-112613.deb,
      name: raspberrypi-bootloader-adafruit-112613.deb
